### ISSUE TITLE
Implement "active document" API for meta datums

### ISSUE THREAD

**Issue by ComFreek** [UFrameIT/UFrameIT#26]
- [x] add untyped constant `labelOf` to theory FrameIT/frameworld@`MetaAnnotations`
- [x] edit all metadatums in scrolls, e.g. `meta ?scrollDescription ... ${labelOf ...?uriOfFactSlotInProblemTheory}`
- [x] implement API in the server component `render(meta: MetaDatum, scrollApplication: PartialScrollApplication)`

**Comment by ComFreek** [comment]
Done. REST API documented at https://github.com/UniFormal/MMT/tree/devel/src/frameit-mmt#rest-api.
